---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pet-battle-api-trigger-template
spec:
  params:
    - name: git-revision
      description: The git revision
      default: master
    - name: git-ref
      description: The full git ref
      default: master
    - name: git-repo-name
      description: The name of the deployment to be created / patched
    - name: git-branch
      description: The git branch name
    - name: git-short-revision
      description: Seven character git sha
    - name: git-app-of-apps-key
      description: App of Apps Key using lowercase
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: $(tt.params.git-repo-name)-
        labels:
          tekton.dev/pipeline: maven-pipeline
          git.branch: $(tt.params.git-branch)
          git.revision: $(tt.params.git-revision)
          git.short.revision: $(tt.params.git-short-revision)
        annotations:
          argocd.argoproj.io/sync-options: Prune=false
          argocd.argoproj.io/compare-options: IgnoreExtraneous
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: maven-pipeline
        params:
          - name: APPLICATION_NAME
            value: $(tt.params.git-repo-name)
          - name: GIT_URL
            value: http://{{ .Values.git_server }}/{{ .Values.team }}/$(tt.params.git-repo-name).git
          - name: GIT_REVISION
            value: $(tt.params.git-revision)
          - name: GIT_SHORT_REVISION
            value: $(tt.params.git-short-revision)
          - name: GIT_REF
            value: $(tt.params.git-ref)
          - name: GIT_BRANCH
            value: $(tt.params.git-branch)
          - name: TEAM_NAME
            value: "{{ .Values.team }}"
        workspaces:
        - name: shared-workspace
          persistentVolumeClaim:
            claimName: build-images
        - name: maven-settings
          configMap:
            name: maven-settings
        - name: maven-m2
          persistentVolumeClaim:
            claimName: maven-m2
        - name: git-auth
          secret:
            secretName: git-auth
        # sonarqube-auth
